workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: 1.14.3
      node: latest
      vars:
        XCODE_WORKSPACE: 'ApkTaxi.xcworkspace'
        XCODE_SCHEME: 'ApkTaxi'
        BUNDLE_ID: 'com.apktaxi.app'
        #DEVELOPMENT_TEAM: 'YOUR_TEAM_ID' # Este es opcional para desarrollo
    scripts:
      - name: Install npm dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --verbose
      - name: Build ipa for development
        script: |
          xcodebuild \
            -workspace "ios/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            -derivedDataPath build/ios \
            build
          cd build/ios/Build/Products/Debug-iphoneos
          mkdir Payload
          cp -r ApkTaxi.app Payload
          zip -r "ApkTaxi.ipa" Payload
    artifacts:
      - build/ios/Build/Products/Debug-iphoneos/ApkTaxi.ipa
