workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
      node: latest
      vars:
        XCODE_WORKSPACE: 'ApkTaxi.xcworkspace'
        XCODE_SCHEME: 'ApkTaxi'
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build for simulator
        script: |
          xcodebuild build \
            -workspace "ios/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14'
    artifacts:
      - build/ios/Build/Products/Debug-iphonesimulator/*.app
