workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: 1.14.3
      node: latest
      vars:
        XCODE_WORKSPACE: 'ApkTaxi.xcworkspace'
        XCODE_SCHEME: 'ApkTaxi'
        BUNDLE_ID: 'com.apktaxi.app'
    scripts:
      - name: Install npm dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --verbose
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles --warn-only
      - name: Build ipa for device
        script: |
          xcodebuild -workspace "ios/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/ios/archive.xcarchive \
            clean archive
          xcodebuild -exportArchive \
            -archivePath build/ios/archive.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
