workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: 1.14.3
      node: latest
      vars:
        XCODE_WORKSPACE: 'ApkTaxi.xcworkspace'
        XCODE_SCHEME: 'ApkTaxi'
        BUNDLE_ID: 'com.apktaxi.app'
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Clean CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod cache clean --all
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --verbose
      - name: Build for device
        script: |
          xcodebuild archive \
            -workspace "ios/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/ios/archive.xcarchive
          xcodebuild -exportArchive \
            -archivePath build/ios/archive.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
