workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: 1.14.3
      node: latest
      vars:
        XCODE_WORKSPACE: 'ApkTaxi.xcworkspace'
        XCODE_SCHEME: 'ApkTaxi'
        BUNDLE_ID: 'com.apktaxi.app'
    scripts:
      - name: Install npm dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --verbose
      - name: Build ipa for development
        script: |
          cd ios
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            -derivedDataPath build \
            build
          cd build/Build/Products/Debug-iphoneos
          mkdir Payload
          cp -r *.app Payload
          zip -r "../../../../../ApkTaxi.ipa" Payload
    artifacts:
      - ApkTaxi.ipa
      - ios/build/**/*.ipa
      - ios/build/Build/Products/**/*.app
