# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'ApkTaxi' do
  config = use_native_modules!

  # Pods para mapas
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps'
  
  # Notificaciones
  pod 'RNNotifee', path: '../node_modules/@notifee/react-native'
  
  # Geolocalización
  pod '@react-native-community/geolocation', path: '../node_modules/@react-native-community/geolocation'
  
  # Sonido
  pod 'RNSound', path: '../node_modules/react-native-sound'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
end
